# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 294f44a75d0d60577ef7fc8b89bcfb398513a4a896bf6aa1d435d8fe87eecd45190a8b313bdc9e75cfddb7e1475717e52c4e1341f3f4bc89bd2de9677900eee2

test:
  secret_key_base: 775f4525c247ff5e6d2d0c9252264622ca300b2581fc0ee84d5b626fe32e689419b8a785234a07b35cf2c1fbe28685cfc688f16da6075d1bbf77d2707a3eefbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
